Ft/add new branch
Samantha-KY/theGym1 pull request #2
Opened 2022-09-19 06:30 UTC by Samiskina

2022-09-19 06:42 UTC, hirwaaldo1 requested changes

2022-09-19 06:42 UTC, hirwaaldo1 commented on style.css
> +}
remove this class in css because it does not have style

2022-09-19 06:51 UTC, hirwaaldo1 approved these changes
it looks good

2022-09-19 07:54 UTC, edson-pro requested changes
format your code and make it quick

2022-09-19 07:54 UTC, edson-pro commented on flexing.html
>      <title>Document</title>
change the title no meaning title

2022-09-19 07:54 UTC, edson-pro commented on flexing.html
> +    <div class="navigate">
remove navigation class

2022-09-19 07:54 UTC, edson-pro commented on flexing.html
> +        <div class="body">
remove body classs

2022-09-19 07:54 UTC, edson-pro commented on flexing.html
> +    <div class= "body__footer">
remove body prefix

2022-09-19 07:54 UTC, edson-pro commented on flexing.html
> +            <p  class="nav__list1 nav__lists--place">Home</p>
nav__lists--place modifier has no reason to use it

2022-09-19 07:54 UTC, edson-pro commented on flexing.html
> +        <div class="body__team">
remove body prefix

2022-09-19 11:04 UTC, edson-pro approved these changes
extravagant

2022-09-19 14:18 UTC, karemarsy reviewed
do some cleanup

2022-09-19 14:18 UTC, karemarsy commented on src/style.css
> +.navv {
why did you name this class `navv`? your naming convention should be clear to everyone

2022-09-19 14:18 UTC, karemarsy commented on src/style.css
> +
remove spaces

2022-09-19 14:18 UTC, karemarsy commented on src/style.css
> +.footer-section {
why didn't use this `footer-section` as an element of `footer`

2022-09-22 10:49 UTC, karemarsy approved these changes

2022-09-27 12:24 UTC, merged